CREATE TABLE REVIEW_BOARD
(
	BOARD_ID INT PRIMARY KEY AUTO_INCREMENT,
	WRITER VARCHAR(20) NOT NULL,
	TITLE VARCHAR(500) NOT NULL,
	CONTENT TEXT,
	WRITE_DATE TIMESTAMP DEFAULT NOW(),
	VIEW_COUNT INT DEFAULT 0
);



CREATE TABLE REVIEW_BOARD_UPLOAD_FILE
(
	FILE_ID INT	PRIMARY KEY AUTO_INCREMENT,
	BOARD_ID INT NULL,
	FILE_NAME VARCHAR(235) NULL,
	FILE_SIZE VARCHAR(45) NULL,
	FILE_CONTENT_TYPE VARCHAR(500) NULL,
	FILE_DATA BLOB NULL
);




ALTER TABLE REVIEW_BOARD_UPLOAD_FILE 
 ADD CONSTRAINT FK_BOARD_BOARD_ID
	FOREIGN KEY (BOARD_ID) REFERENCES REVIEW_BOARD (BOARD_ID);




